### ISSUE TITLE
Jax serialization of tff.types.StructType

### ISSUE THREAD

**Issue by timdhondt1** [tensorflow/federated#1434]
I am trying to implement the client update step in JAX while making use of the `jax.experimental.stax` module for the definition of my model. Initialized model weights are given as Jax TracedArray objects. However, serializing a function that takes model weights as a struct of jax TracedArray objects gives the error

`AttributeError: The `Struct` of length 2 does not have named field "tensor_index". Fields (up to first 10): []`

A short reconstruction of the error can be found [here](https://colab.research.google.com/drive/1NAsV7yfVQZv-izRTer2vBstoaEZsUh8H?usp=sharing)

It seems that `get_model_weights.type_signature.result` returns a nested `tff.StructType` object. The arrays at the bottom of this nested structure are correctly identified as `tff.TensorType`. However, the error I get keeps throwing `AttributeError: The `Struct` of length 2 does not have named field "tensor_index". Fields (up to first 10): []`. 

After looking into `tensorflow_federated/python//core/impl/jax_context/jax_serialization.py`, I found that the problem lies in line 147-148:

```
flattened_obj, _ = jax.tree_util.tree_flatten((args, kwargs))  
tensor_indexes = list(np.argsort([x.tensor_index for x in flattened_obj]))
```

`flattened_obj` does not seem to be flattened, there is still a `StructType` object nested in the list, which causes `x.tensor_index` to fail in the next line. 

Any suggestions on how this can be solved?

**Comment by jkr26** [comment]
Looking at this code, I think there is a bug here with nested structures. Writing a failing test now, will tag this issue

**Comment by jkr26** [comment]
Should be resolved by [9e1edc7](https://github.com/tensorflow/federated/commit/9e1edc7fc86b014642a1bfde263d89f035f94ba3); when TFF-Nightly is released overnight the fix should be usable.

**Comment by timdhondt1** [comment]
Problem still seems to be there after the update. [See the same colab file again](https://colab.research.google.com/drive/1NAsV7yfVQZv-izRTer2vBstoaEZsUh8H?usp=sharing). Tff-nightly is up to date as can be seen.

It gives the same output as before the fix.

**Comment by jkr26** [comment]
assigning @zcharles8 to this, he is taking a look at fleshing out TFF Jax relationship in Python, I think in particular what is failing at the moment.
